using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Xml;

namespace DumativaHeart
{
    static class Save
    {

        public static int hardBeatConsequence, mediumBeatConsequence, weakBeatConsequence;
        public static string textoAtual,textoDecisao;

        public static void lerXml(int indexCena)
        {
            XmlDocument documento = new XmlDocument();
            try
            {
                documento.Load("notASaveFile.xml");
            }

            catch
            {
                criarXmlInicial();
                documento.Load("notASaveFile.xml");
            }

            //Leitura Textos
            textoAtual = (documento.SelectSingleNode("Informacoes/Textos/Cena"+indexCena).Attributes[0].Value);
            hardBeatConsequence = int.Parse(documento.SelectSingleNode("Informacoes/Textos/Cena" + indexCena).Attributes[1].Value);
            mediumBeatConsequence = int.Parse(documento.SelectSingleNode("Informacoes/Textos/Cena" + indexCena).Attributes[2].Value);
            weakBeatConsequence = int.Parse(documento.SelectSingleNode("Informacoes/Textos/Cena" + indexCena).Attributes[3].Value);
            textoDecisao = (documento.SelectSingleNode("Informacoes/Textos/Cena" + indexCena).Attributes[4].Value);

        }

        public static void criarXmlInicial()
        {
            XmlWriterSettings settings = new XmlWriterSettings();

            settings.Indent = true;
            XmlWriter writer = XmlWriter.Create("notASaveFile.xml", settings);

            writer.WriteStartDocument();
            writer.WriteComment("Esse arquivo foi escrito pelo Rodrigostoso Forti PRA CARALHO, pelo Pequeno Bringelado e pelo Marcos Pólos");
            writer.WriteStartElement("Informacoes");

            writer.WriteStartElement("Textos");
            newTexto(writer, 0, "My eyes are open, hurt by a strong light, soon my mind slowly start to process. Even so, things don't make much sense.I try to remember how I got here but nothing else helps me to understand this situation. I look around and I see the curtains, metallic objects, syringes. Besides, There is a person lying in other bed next to me. He (or she) is unconscious. I noticed little tubes followed by a needle, pierced inside my arm.", 2, 1, 1, "But why ? Why all this is happening to me ?");
            newTexto(writer, 1, "I can't be sure of nothing, no memories come to me, Only doubts that chase me again and again. Suddenly, a nurse enters in my room and freaks out. Maybe I wasn't suppose to be awake. She trys to act normal, and ask me how I'm and for how long i'm conscious. At this moment I realize :", 7, 7, 8, "I don't remember who I am.");
            newTexto(writer, 2, "These things hurts like hell. I rip them off and get up as fast as I can searching for clues to understand what is going on and what I'm suppose to do. I notice two clipboards on the table .", 3, 3, 4, "However the names are written with some sort of a number combination. While I'm checking these files, a nurse comes inside the room.");
            newTexto(writer, 3, "For some reason she freaks out. Maybe I wasn't suppose to be awake. I ask her what is the meaning of all this, where I'm and why I'm here. The nurse hesitates for a moment. That was enough for me. I move towards her but now she is really scared. She loses control and runs out of the room.", 12, 11, 11, "I take advantage of the situation and get back the forms, It must have something i'm missing.");
            newTexto(writer, 4, "For some reason she freaks out. Maybe I wasn't suppose to be awake. I ask her what is the meaning of all this, where I'm and why I'm here. The nurse hesitates for a moment and ask for patience. I understand that it is the best thing I can do at this moment. I sit on my bed and she say that she will call the responsible doctor. ", 6, 5, 5, "Something is not right. Before she leaves I decide to take two clipboards with some forms.");
            newTexto(writer, 5, "I ask to the nurse to read those forms. She tells me that the forms are complicated and that the doctor will explain them to me soon .It's a good point. I lie on my bed again, a little more controlled. The medic arrives and ask me if I'm ok. I say 'yes' and start to ask him some questions. He tells me that will explain everything while he gives one more dose of my serum. Suddenly my blood pressure starts to get lower. Before a completaly loose it, I noticed a strange object in his hands. He is injecting some substance in my serum. Something is very wrong. ", 41, 41, 41, "Before I can react, I faint."); // MARCO 1
            newTexto(writer, 6, "I ask to the nurse to read those forms. She tells me that the forms are complicated and that the doctor will explain them to me soon .I disagree with her and tell her it is senseless. I lose control and I move towards her. Extremelly scared she freaks out and starts to run screaming for heal. Soon, I find myself surrounded by maale nurses and one of them injects me with some sort of substance that lowers my blood pressure quickly. Suddenly, I faint.", 40, 40,40, ""); // MARCO 1
            newTexto(writer, 7, "The nurse gets near me afterwards with a stetoscope in hand. She probably wants to measure my heart rate. Impulsively, I grab her arm tightly and almost voiceless I tell her I can't remember a thing. Without realizing I'm hurting her, I demand explanations. ", 10, 9, 9, "My confusion frightens her and with an abrupt gesture she backs off and leaves saying she'll bring the doctor resposible for the ward.");
            newTexto(writer, 8, "The nurse comes near me afterwards but I think it might not be convenient to let them know I can't remember anything. I ask her to call a doctor so he can check on my situation. The nurse then leaves the room and I start to check my surroundings. I notice two clipboards.", 12, 11, 11, "They seem to have information about my and the other patient identification");
            newTexto(writer, 9, "With much effort, I manage to calm myself down and apologize to the nurse.I tell her, again, that I can't remember a thing. She then reassures me I'll be fine as soon as she calls my doctor, who will answer all my questions. After she leaves, I stay in the room in the company only of my unknown roomate, who's still unconscious. I notice two clipboards over the bedside table. I decide to sit on the bed and check the prontuaries, while the doctor is not there yet.", 12, 11, 11, "Both are totally filled out, with the exception of the 'NAME' field, which is filled with random numbers.");
            newTexto(writer, 10, "I lose control, pull off the wires and tubes attached to me and charge towards the nurse, demanding an immediate explanation. Extremely scared and visibly reactionless, she backs off towards a nearby wall and screams for help. Suddenly, I'm surrounded by male nurses, and one of them applies an injection of some substance that lowers my blood pressure quickly. Suddenly, I faint.", 42, 42, 42, "");//MARCO 1
            newTexto(writer, 11, "The information contained won't help me in anything to know who I am, since my age and the other patient's are practically the same. Near the forms, there is a pen, but as far as I can see there's no other paper in the room aside from the documents.To avoid suspicion, I write down the codes in my own skin.At that moment a doctor arrives.", 16, 15, 15, "Must be my medic who'll explain to me what's going on exactly.");
            newTexto(writer, 12, "The information in the forms don't help me at all at knowing who I am, since my age and the other patient's are the same.I take a quick look around but can't find anything to write down the codes with. ", 13, 13, 14, "I decide to rip out the forms off the clipboards and hide them somewhere.");
            newTexto(writer, 13, "There aren't many places where I can hide the pages, so, by impulse, I put them under my bedsheets. Shortly afterwards, a doctor comes in.I try to evade his questions saying 'I'm fine' just so I can get out as soon as possible. He notices the missing forms and appears to suspect something, as if something unusual was going on. He calls the nurses who quickly immobilize me while he injects me some substance, claiming it is for my own good. My senses slowly fade away and I faint.", 40, 40, 40, ""); // MARCO 1
            newTexto(writer, 14, "There arent many places to hide the pages, so I think about putting them under my sheets.I then realize that's the most obvious hiding place, so I put them under the other patient's sheets instead. Shortly afterwards, a doctor comes in. I try to evade his questions saying 'I'm fine' just so I can get out as soon as possible. He notices the missing forms and appears to suspect something, as if something unusual was going on. He calls the nurses who quickly immobilize me while he injects me some substance, claiming its for my own good.My senses slowly fade away and I faint.", 43, 43, 43, ""); // MARCO 1
            newTexto(writer, 15, "Although extremely confused, I pretend to be calm. The doctor asks me if I'm fine. I say 'Yes' and ask him what is going on and how I got here. He says he'll tell me everything while he changes my medicine. Suddenly, my pressure starts dropping. Before my senses fade completely, I see something strange in his hands, as if he were injecting something in my medicine. Without being able to react, I black out", 18, 18, 18, "");// MARCO 1
            newTexto(writer, 16, "I decide to ask the doctor about my situation. Visibly upset, he evades my questions and says I should calm myself. He tries to switch my medicine but I suspect his actions. At that moment, I stop him and try to grab his arm while still bombarding him with questions. He backs off while I pull off the wires attached to me and attack him. Suddenly, I'm surrounded by nurses. One of them applies me some substance that makes my pressure drop, and I suddenly faint.", 25, 25, 25, "");//MARCO 1
            newTexto(writer, 17, "Although extremely confused, I pretend to be calm. The doctor asks me if I'm fine. I say 'Yes' and ask him what is going on and how I got here. He says he'll tell me everything while he changes my medicine. Suddenly, my pressure starts dropping. Before my senses fade completely, I see something strange in his hands, as if he were injecting something in my medicine. Without being able to react, I black out.", 25, 25, 25, "");// MARCO 1

            newTexto(writer, 18, "Again I wake up in my bed, only remembering the doctor sedating me. I don't know the  reason, but they don't want me awake. Again I look around, seeing a security guard in front of the bedroom's door.", 19, 20, 20, "There's definitely something wrong here. I need to get out of this room immidietal, but I stil don't know how.");
            newTexto(writer, 19, "I need to get rid of these tubes again, but now with other plans: I can use them in my favour. I test the resistance of one of them, they don't break easy. Perfect! Sneackily, I get up from my bed and head to the door, with cautious feet. I must open the door with the utmost calm, avoiding any noise.", 21, 22, 22, "While I pull the door carefully, I prepare to act with extreme energy and agility, while I try to strangle the security guard… ");
            newTexto(writer, 20, "I try to find a way to fool the security guard, leaving the exit of the rom free. It takes a while, but I see a glass and decide to ask for some water. I can't think of any better ideas, but I have to risk it. ", 24, 23, 23, "I call the security  guard,  which  listens  and  open  the  door,  coming  closer.  I  have  to  be  convincing  and  pretend tranquility in my request. ");
            newTexto(writer, 21, "With some work, I manage to strangle the guard, and hide him in the room. With the way free, I examine the place: there's a long hallway, crossed by many others. Without guidance this place is a maze. Still, I go through the hallways, until I manage to find a map of the sectors. I don't know what exactly to look for, I only have two form codes. One particular sector draws my attention: the archives room. While I try to memorize its location, I hear footsteps coming in my direction.", 35, 35, 34, "I slide in a tiny gap on the wall, I have to stay completely immobile or I'll be discovered. ");
            newTexto(writer, 22, "Unfortunately I didn't applied enough  strength and  was  easily  overwhelmed  by  the  security  guard.  I panicked  and  tried  to  push  him  away,  but  he  immobilized  me  with  a  Taser  gun.", 18, 18, 18, "");//LOOP 18
            newTexto(writer, 23, "The security guard is convinced by my apparent tranquility and leaves to find a nurse, leaving the way free. I get out of my room and examine the place: there's a long hallway, crossed by many others. Without guidance this place is a maze. Still, I go through the hallways, until I manage to find a map of the sectors. I don't know what exactly to look for, I only have two form codes. One particular sector draws my attention: the archives room. While I try to memorize its location, I hear footsteps coming in my direction.", 35, 35, 34, "I slide in a tiny gap on the wall, I have to stay completely immobile or I'll be discovered.");
            newTexto(writer, 24, "I  tried  to  remain  calm,  but my  body  betrays  me as  I  think  on  the  possibility  of  being  discovered.  The security guard suspects of my nervous behavior and warns the doctor, which alerts security and sedates me once again.", 18, 18, 18, ""); // LOOP 18
            newTexto(writer, 25, "Again I wake up in my bed, only remembering the doctor sedating me. My arms are strapped to the bed, I'm starting to think they don't want me awake. Strangest of all is the security guard, now posted outside the bedroom's door.", 26, 27, 27, "I have to get free, before the doctor or some nurse comes in and notices I'm awake again. I have to force my hands fee. ");
            newTexto(writer, 26, "With quick and forceful moves, I manage to loose the straps  just enough to get my hands free. But I'm not yet free, the door is still blocked by the security guard, that don't seem to want to go anywhere anytime soon. ", 19, 28, 28, "I just know there's something wrong here. I have to leave this room immediately, but I still don't know how. ");
            newTexto(writer, 27, "I didn't tried hard enough, the security guard notices my agitation and alerts the doctor, which sedated me again.", 25, 25, 25, "");// LOOP 25
            newTexto(writer, 28, "Maybe I can make the security guard go away with some kind of plan, but there isn't much to use in the room. My only  chance  is to pretend  something  is  wrong  with  me, to  make  him  go  get  help  and  ignore the fact that I have broken free. ", 29, 30, 29, "My idea is to fake a seizure, but I have to be convincing so it doesn't looks like I'm faking it.");
            newTexto(writer, 29, "Apparently,  my  acting  convinced  the  guard,  that  looked  disturbed, and  ran  off  quickly to  get  aid. With the way free, I get out of my room and examine the place: there's a long hallway, crossed by many others. Without  guidance this  place  is  a  maze.  Still,  I  go  through  the  hallways, until  I manage  to  find  a map of the sectors. I don't know what exactly to look for, I only have two form codes. One particular sector  draws  my  attention:  the  archives  room.  While  I  try  to  memorize  its  location,  I  hear  footsteps coming in my direction.", 35, 35, 34, "I slide in a tiny gap on the wall, I have to stay completely immobile or I'll be discovered. ");
            newTexto(writer, 30, "My sorry excuse for acting didn't seem  to  impress  the  security  guard, that  noticed  the  trick  and immobilized me. ", 25, 25, 25, ""); // LOOP 25
            newTexto(writer, 31, "With quick and forceful moves, I manage to loose the straps  just enough to get my hands free. But I'm not yet free, the door is still blocked by the security guard, that don't seem to want to go anywhere anytime soon. I look under my sheet, looks like the doctor discovered where I hid the form pages, since they are gone.",19,28,28,"Now I know there's something wrong. I have to leave this room immediately, but I still don't know how.");
            newTexto(writer, 32, "With quick and forceful moves, I manage to loose the straps  just enough to get my hands free. I look around the room, looking for any clues that might explain something. I discover clipboards with forms, on the bedside. As I read them, I notice that both 'NAME' fields are filled with alphanumeric codes. ", 19, 28, 28, "There's something wrong here. I have to leave this room immediately, but I still don't know how.");
            newTexto(writer, 33, "With quick and forceful moves, I manage to loose the straps  just enough to get my hands free. But I'm not yet free, the door is still blocked by the security guard, that don't seem to want to go anywhere anytime soon. I look under the sheet of the bed next to me and get the form pages. I'm sure they'll be helpful.", 19, 28, 28, "Anyway, I know there's something wrong. I have to leave this room immediately, but I still don't know how. ");
            newTexto(writer, 34, "I held my breath as long as I could, the security guard didn't noticed me and continued on his way. Now I go through the hallways, after the archives room - fortunately it doesn't take me long to find it, without  bumping  into  any  security  guards.  I  open  the  door  with  caution,  noticing  with  relief,  that  the room  is  empty.  I  come  in  and  close  the  door  behind  me,  carefully.  But  it  gets  clear  that  finding  the information I seek won't be an easy task: ", 39, 39, 38, "There  are  lots  of cabinets, files, drawers… I stop for a moment and think about what to do. ");
            newTexto(writer, 35, "The  situation  was  too  intense, I didn't managed to contain my  heavy  breathing.  With  this  slip,  the security guard heard me. The footsteps start coming again in my direction, as I hear the footsteps, I get even  more  nervous. ", 36, 37, 37, "Finally  he  finds  me,  he  hesitates  for  a  second  and  then  attacks,  trying  to immobilize me like I'm his pray.");
            newTexto(writer, 36, "Fighting against my own limits, I find the strength to fight him off, bashing his head against the wall and leaving him unconscious. Quickly I see a store room, nothing more perfect to hide him. Now I seek the archives room - fortunately it doesn't take me long to find it, without bumping into any security guards. I open the door with caution, noticing with relief, that the room is empty. I come in and close the door behind me, carefully. But it gets clear that finding the information I seek won't be an easy task: ", 39, 39, 38, "There are lots of cabinets, files, drawers… I stop for a moment and think about what to do. ");
            newTexto(writer, 37, "The first strike from the security guard hits me spot on. I can't find the energy to fight back. I'm easily dominated and taken back to the medical ward.", 18, 18, 18, "");
            newTexto(writer, 38, "I look the codes written on my skin, E23 and S01, I notice there's some meaning to them. Immediately I see a cabinet with drawers in alphabetic order, it's my first try. With the codes, I find two identification files - curiously, there's only one with the letter S. I have now two names: John Franklin and George summers,  43  and  41 years  old,  no  pictures.  Only  the  information  that  John  was  in  a  coma  for  seven months, and George for almost two and a half years, besides the numbers of drawers with 'personal belongings'. Nothing that indicate switch one is me. As I feel that I'm finally starting to shed some light into  all  of  this,  I  look  around  and  spot  a  shelf with  labels,  among  them 'SUBJECTS' and 'EXPERTS'.  I search  the  rooms and 'bingo':  I  find files  with the historic of Franklin  and  Summers.  As  I'm about to open them I hear suspicious movements, I have to escape quickly. ", 47, 47, 47, ""); // Levam pro Final 1
            newTexto(writer, 39, "I look the codes written on my skin, E23 and S01, I notice there's some meaning to them. Immediately I see a cabinet with drawers in alphabetic order, it's my first try. With the codes, I find two identification files - curiously, there's only one with the letter S. I have now two names: John Franklin and George summers,  43  and  41 years  old,  no  pictures.  Only  the  information  that  John  was  in  a  coma  for  seven months, and George for almost two and a half years, besides the numbers of drawers with 'personal belongings'. Nothing that indicate switch one is me. I feel so  nervous that  I can't even think  straight,  I can only think of the danger I'm in right now, in this archives room. I hear lots of suspicious movements, my nerves are on the edge, I'm scared, I can't get caught. I have to escape quickly.", 48, 48, 48, ""); // Levam pro Final 2
            newTexto(writer, 40, "Again I wake up in my bed, only remembering the doctor sedating me. My arms are strapped to the bed, I'm starting to think they don't want me awake. Strangest of all is the security guard, now posted outside the bedroom's door.", 31, 44, 44, " I have to get free, before the doctor or some nurse comes in and notices I'm awake again. I have to force my hands fee.");
            newTexto(writer, 41, "Again I wake up in my     bed, only remembering the doctor sedating me. I don't know the  reason, but they don't want me awake. Again I look around, seeing a security guard in front of the bedroom's door. ", 19, 20, 20, "There's definitely something wrong here. I need to get out of this room immediately, but I stil don't know how.");
            newTexto(writer, 42, "Again I wake up in my bed, only remembering the doctor sedating me. My arms are strapped to the bed, I'm starting to think they don't want me awake. Strangest of all is the security guard, now posted outside the bedroom's door.", 32, 45, 45, "I have to get free, before the doctor or some nurse comes in and notices I'm awake again. I have to force my hands fee.");
            newTexto(writer, 43, "Again I wake up in my bed, only remembering the doctor sedating me. My arms are strapped to the bed, I'm starting to think they don't want me awake. Strangest of all is the security guard, now posted outside the bedroom's door.", 33, 46, 46, "I have to get free, before the doctor or some nurse comes in and notices I'm awake again. I have to force my hands fee.");
            newTexto(writer, 44, "I didn't tried hard enough, the security guard notices my agitation and alerts the doctor, which sedated me again.", 40, 40, 40,"");
            newTexto(writer, 45, "I didn't tried hard enough, the security guard notices my agitation and alerts the doctor, which sedated me again.", 42, 42, 42,"");
            newTexto(writer, 46, "I didn't tried hard enough, the security guard notices my agitation and alerts the doctor, which sedated me again.", 43, 43, 43,"");
            newTexto(writer, 47, "You  are  still  stuck in  the  hospital, and don't remember  anything,  but made  important  steps in  your search. John Franklin or George summers? Subject or expert? Escaping the hospital is not enough, you have much do discover yet. Personal belongnings drawer? Historic files? You've come along way and is on the right track, but is still ONLY THE BEGINING.  ", 0, 0, 0, "To be Continued...");
            newTexto(writer, 48, "You  are  still  stuck in  the  hospital, and don't remember  anything,  but made  important  steps in  your search. John Franklin or George summers? Subject or expert? Escaping the hospital is not enough, you have much do  discover  yet.  Personal belongings drawer? You've  come  a  long  way  and  may  have  lost some valuable information about your past, but is still ONLY THE BEGINING. ", 0, 0, 0, "To be Continued...");

            writer.WriteEndElement();

            writer.WriteEndDocument();
            writer.Flush();
            writer.Close();
        }

        public static void newTexto(XmlWriter writer, int indexCena, string texto, int hardBeatConsequence, int mediumBeatConsequence, int weakBeatConsequence, string textoDecisao)
        {
            writer.WriteStartElement("Cena"+indexCena.ToString());
            writer.WriteAttributeString("texto",texto);
            writer.WriteAttributeString("hardBeatConsequence", ((int)(hardBeatConsequence)).ToString());
            writer.WriteAttributeString("mediumBeatConsequence", ((int)(mediumBeatConsequence)).ToString());
            writer.WriteAttributeString("weakBeatConsequence", ((int)(weakBeatConsequence)).ToString());
            writer.WriteAttributeString("textoDecisao", textoDecisao);
            writer.WriteEndElement();

        }

   
    }
}
